name: apk

on:
  push:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Assemble Release
    - run: |
        chmod +x ./gradlew
        ./gradlew build
        ./gradlew assembleRelease
    - name: Publish GitHub Release
      uses: fnkr/github-action-ghr@v1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GHR_PATH: app/app-debug.apk
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
